openapi: 3.0.0
info:
  title: Services APP
  description: App to book services
  version: 1.0.0

servers:
  - url: http://localhost:3005


paths:
  /api/v1/auth/register:
    post:
      summary: Register User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User successfully registered
        "400":
          description: Request Error

  /api/v1/auth/login:
    post:
      summary: User authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Success
        "401":
          description: Error
